[project]
name = "cot-pl0-compiler"
version = "0.1.0"
description = "A toy compiler from PL/0 to Aarch64"
readme = "README.md"
requires-python = ">=3.10"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.12",
    "ty>=0.0.34",
]

[tool.ruff]
target-version = "py310"
line-length = 80

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = ["src"]
